name: work38
channels:
  - tensorly
  - pytorch
  - huggingface
  - conda-forge
dependencies:
  - python>=3.8, <3.9
  - pytorch=1.12.1
  - cudatoolkit=11.3.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - librosa=0.9.2
  - onnx=1.10.2
  - onnx2torch=1.5
  - pandas=1.4.2
  - pip=21.2.4
  - pyopengl=3.1
  - pyrender=0.1.45
  - pyvista=0.35
  # - pyvistaqt=0.10
  - pyvistaqt
  - resampy=0.2.2
  - scikit-image=0.19.2
  - scikit-learn=1.0.2
  - scikit-video=1.1.11
  - seaborn=0.11.0
  - tensorly=0.6.0
  - pip:
    - albumentations==1.0.3
    - compress-pickle==1.2.0
    - chumpy==0.70
    - Cython==0.29
    - decord==0.6.0
    - face-alignment==1.3.5
    - facenet-pytorch==2.5.2
    - gdown==4.5.1
    - h5py==3.8.0
    - hickle==5.0.2
    - huggingface-hub==0.16.4
    - hydra-core==1.0.7
    - imgaug==0.4.0
    - insightface==0.6.2
    - kornia==0.6.5
    - matplotlib==3.2.2
    - mediapipe==0.8.10
    - munch==2.5.0
    - numpy==1.23.0
    - onnxruntime-gpu==1.9.0
    - opencv-contrib-python==4.7.0.72
    - opencv-python==4.7.0.72
    - opencv-python-headless==4.7.0.72
    - psbody-mesh @ git+https://github.com/MPI-IS/mesh.git@v0.4
    - python-speech-features==0.6
    - pytorch-lightning==1.4.9
    - pytorch3d @ git+https://github.com/facebookresearch/pytorch3d.git@v0.6.2
    - torchgeometry==0.1.2
    - torchmetrics==0.6.2
    - torchfile==0.1.0
    - transformers==4.22.2
    - trimesh==3.6.43
    - wandb==0.10.33


